# Generated by Django 3.1.1 on 2020-10-01 09:02

from django.db import migrations, models
import djangotango.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(default='default.png', storage=djangotango.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
